export const FETCH_30_REQUEST = 'FETCH_30_REQUEST';
export const FETCH_30_SUCCESS = 'FETCH_30_SUCCESS';
export const FETCH_30_FAILURE = 'FETCH_30_FAILURE';
export const FETCH_ALL_REQUEST = 'FETCH_ALL_REQUEST';
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS';
export const FETCH_ALL_FAILURE = 'FETCH_ALL_FAILURE';
